telegram:
  bot:
#    не вписывайте данные, так как можете отправить в публичный репозиторий
#    используйте переменные среды для установки значений
    username: ${BOT_NAME}
    token: ${BOT_TOKEN}
    check:
      value: 02
      unit: MINUTES
    notify:
      delay:
        value: 10
        unit: MINUTES

binance:
  api:
    getPrice: https://api.binance.com/api/v3/avgPrice?symbol=BTCUSDT


spring:
  datasource:
#    primary:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
#    secondary:
#      driverClassName: org.h2.Driver
#      url: jdbc:h2:mem:shedlock_DB;INIT=CREATE SCHEMA IF NOT EXISTS shedlock;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#      username: sa
#      password:

