telegram:
  bot:
#    не вписывайте данные, так как можете отправить в публичный репозиторий
#    используйте переменные среды для установки значений
    username: bitcoin_redyarsk_bot
#    ${BOT_NAME}
    token: 6441158073:AAE7vG-M1CqXUF_uZlxqE1nBt_DPzAKV7A0
#    ${BOT_TOKEN}
    check:
      value: 01
      unit: MINUTES
    notify:
      delay:
        value: 03
        unit: MINUTES

binance:
  api:
    getPrice: https://api.binance.com/api/v3/avgPrice?symbol=BTCUSDT


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password


